version: "3.8"
services:
  api:
    build: ../svc-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  ml:
    build: ../svc-ml
    command: uvicorn src.server:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
  renderer:
    build: ../svc-renderer
    command: uvicorn src.server:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"