name: travel_app
environment: { sdk: '>=3.0.0 <4.0.0' }
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.2
  sqflite: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter