name: Flutter CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.24.0' }
      - name: Pub get & Analyze
        run: |
          cd app-mobile
          flutter pub get
          flutter analyze
      - name: Tests
        run: |
          cd app-mobile
          flutter test
